name: beacons_plugin
description: This plugin makes it easier to scan nearby iBeacons and range them in flutter app. Scaned beacons will provide proximity values.
version: 2.0.8
homepage: https://github.com/umair13adil/simple_beacons_flutter

environment:
  sdk: ">=3.1.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter 

flutter:
  plugin:
    platforms:
      android:
        package: com.umair.beacons_plugin
        pluginClass: BeaconsPlugin
      ios:
        pluginClass: BeaconsPlugin
